timesheet/config/routes.rb
Rails.application.routes.draw do
  resources :timesheets

  root 'timesheets#index'

end

timesheet/app/models/mtimesheet.rb
class Mtimesheet < ActiveRecord::Base
end

timesheet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

timesheet/app/controllers/timesheet_controller.rb
class TimesheetController < ApplicationController
  def index
  end
end

timesheet/app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
	def index
		@ctimesheet = Mtimesheet.all
	end

	def show

	end

	def new

	end

	def create
		@timesheet = Mtimesheet.new(timesheets_param)
		#render plain: timesheets_param.inspect
		@timesheet.save
		redirect_to action: 'index'
	end

	def destroy
  		@timesheet = Mtimesheet.find(params[:id])
  		@timesheet.destroy
  		redirect_to action: 'index'
	end

    private
    def timesheets_param
    	params.require(:mtimesheet).permit(:project,:description,:hours,:status)
    end
end

timesheet/app/helpers/application_helper.rb
module ApplicationHelper
end

timesheet/app/helpers/timesheet_helper.rb
module TimesheetHelper
end

timesheet/app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

timesheet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timesheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

timesheet/app/views/timesheets/index.html.erb
<!DOCTYPE html>
<html>
        <head>
                <!--<link type="text/css" rel="stylesheet" href="stylesheet.css">-->
                <title>Timesheet</title>
        </head>
<body>

 <h3><center>Timesheets</center></h3>
 <button id="addCF">Add</button>
<%= form_for :mtimesheet, url: timesheets_path do |timesheet| %>
       
        <table class="form-table" id="customFields">
         <th><label for="Project">Project</label></th>
         <th align="center"><label for="Description">Description</label></th>
         <th align="center"><label for="Hours">Hours</label></th>
         <th align="center"><label for="Status">Status</label></th>
         

         <tr valign="top">
            <td align="center"><%= timesheet.text_field :project %></td>
            <td align="center"><%= timesheet.text_field :description %></td>
            <td ><%= timesheet.select :hours, [['1', 1], ['2', 2], ['3',3]] %></td>
            <td align="center"><%= timesheet.select :status, [['Completed',11],['Pending',12]] %></td>
            


            <td colspan="10"><a href="javascript:void(0);" class="remCF">Remove</a></td>&nbsp;
         </tr>
        </table>
        <p>
         <%= timesheet.submit %>
        </p>    
<% end %>

    <% @ctimesheet.each do |times| %>
         <tr valign="top">
            <td align="center"><%= times.project %></td>
            <td align="center"><%= times.description %></td>
            <td align="center"><%= times.hours %></td>
            <td align="center"><%= times.status %></td>
            <td><%= link_to 'Destroy',timesheet_path(times),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
         </tr>
         <% end %>



<script src="app/assets/javascripts/jquery.js"></script>

<script>
$(document).ready(function() {
    $(".remCF").on('click',function(){
        removeRecord(this);
    });
    $("#addCF").click(function() {
        $("#customFields").append('<tr><td><%= text_field(:mtimesheet, :project) %></td><td><%= text_field(:mtimesheet, :description) %></td><td><%= escape_javascript(select(:mtimesheet, :hours,[['1',1],['2',2],['3',3]])) %></td><td><%= escape_javascript(select(:mtimesheet, :status,[['Completed',11],['Pending',12]])) %></td>escape_javascript<td colspan="10"><a href="javascript:void(0);" class="remCF">Remove</a></td>&nbsp;</tr>');
        $(".remCF").unbind('click');
        $(".remCF").on('click',function(){
        removeRecord(this);
        });
    });
});
    function removeRecord(ele){
    var a = confirm("Do you wish to continue?");
    if(a){
        $(ele).parent().parent().remove();
    }
}

</script>
</body>
</html>

timesheet/app/views/timesheets/show.html.erb
<!DOCTYPE html>
<html>
        <head>
                <!--<link type="text/css" rel="stylesheet" href="stylesheet.css">-->
                <title>Timesheet</title>
        </head>
<body>

<h3><center>Timesheets</center></h3>
<%= form_for :timesheet, url: timesheets_path do |timesheet| %>
		<button id="addCF">Add</button>
	    <table class="form-table" id="customFields">
	     <th><label for="Project">Project</label></th>
	     <th align="center"><label for="Description">Description</label></th>
	     <th align="center"><label for="Hours">Hours</label></th>
	     <th align="center"><label for="Status">Status</label></th>
	 	 <tr valign="top">
		    <td><%= timesheet.text_field :project %></td>
		    <td><%= timesheet.text_field :description %></td>
		    <td><%= timesheet.select :hours, [['1', 1], ['2', 2], ['3',3]] %></td>
		    <td><%= timesheet.select :status, [['Completed',11],['Pending',12]] %></td>
	        <td colspan="10"><a href="javascript:void(0);" class="remCF">Remove</a></td>&nbsp;
		 </tr>
	    </table>
		<p>
   		 <%= timesheet.submit %>
  		</p>    
<% end %>

<script src="jquery.js"></script>

<script>
$(document).ready(function() {
    $(".submitCF").on('click',function(){
        submitRecord(this);
    }); 
      $(".remCF").on('click',function(){
        removeRecord(this);
    });

    
  $("#addCF").click(function() {

    $("#customFields").append('<tr valign="top"><td><input type="text" class="code" id="Project" name="Project[]" value="" placeholder="Project Name" /> &nbsp;</td><td><input type="text" class="code" id="Description" name="Description[]" value="" placeholder="Description" /> &nbsp;</td><td><select class="code" id="Hours" name="Hours[]"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option></select>&nbsp;</td><td><select class="code" id="Status" name="Status[]" ><option value="Completed">Completed</option><option value="Pending">Pending</option></select> &nbsp;</td><td><a href="javascript:void(0);" class="submitCF">Submit</a></td><td><a href="javascript:void(0);" class="remCF">Remove</a></td></tr>');
    /*.on()Attach an event handler function for one or more events to the selected elements.*/
    /*.parent()Get the parent of each element in the current set of matched elements, optionally filtered by a selector.*/
    $(".submitCF").unbind('click');
    $(".submitCF").on('click',function(){
        submitRecord(this);
    });
    $(".remCF").unbind('click');
      $(".remCF").on('click',function(){
        removeRecord(this);
    });
      
  });
});

function submitRecord(ele){
    alert("Details are entered");
}

function removeRecord(ele){
    var a = confirm("are you sure");
    if(a){
        $(ele).parent().parent().remove();
    }
}

</script>

</body>
</html>